name: ItemLock
main: xyz.acrylicstyle.itemlock.ItemLock
version: 0.0.1-SNAPSHOT
api-version: 1.20
commands:
  ilock:
    description: "Locks item lock"
  iunlock:
    description: "Unlocks item lock"
