name: ItemLock
main: xyz.acrylicstyle.itemLock.ItemLock
version: 0.0.1-SNAPSHOT
api-version: "1.15"
depend:
  - TomeitoLib
commands:
  ilock:
    description: "Locks item lock"
  iunlock:
    description: "Unlocks item lock"
  ifind:
    description: "Find."